[build]
  command = "npm run netlify:build"
  publish = "build/client"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  DATABASE_PROVIDER = "postgresql"

# Environment variables for production
[context.production.environment]
  DATABASE_PROVIDER = "postgresql"
  NODE_ENV = "production"

# Environment variables for branch deploys
[context.branch-deploy.environment]
  DATABASE_PROVIDER = "postgresql"
  NODE_ENV = "production"

# Environment variables for deploy previews
[context.deploy-preview.environment]
  DATABASE_PROVIDER = "postgresql"
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"